-- Admin access control schema for Studio TFA
--
-- IMPORTANT:
-- This schema supports IP-only admin mode (no login required).
-- Access is enforced by your Next.js proxy layer and server checks.

-- ==============================
-- 1) Settings table (singleton)
-- ==============================
create table if not exists public.admin_access_settings (
  id text primary key,
  allowed_ips text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.admin_access_settings (id, allowed_ips)
values ('singleton', '127.0.0.1')
on conflict (id) do nothing;

create or replace function public.touch_admin_access_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_admin_access_settings_updated_at on public.admin_access_settings;
create trigger trg_admin_access_settings_updated_at
before update on public.admin_access_settings
for each row
execute function public.touch_admin_access_settings_updated_at();

alter table public.admin_access_settings enable row level security;

drop policy if exists master_admin_select_settings on public.admin_access_settings;
drop policy if exists master_admin_upsert_settings on public.admin_access_settings;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_settings'
      and policyname = 'admin_access_settings_read'
  ) then
    create policy admin_access_settings_read
      on public.admin_access_settings
      for select
      to anon, authenticated
      using (id = 'singleton');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_settings'
      and policyname = 'admin_access_settings_write'
  ) then
    create policy admin_access_settings_write
      on public.admin_access_settings
      for all
      to anon, authenticated
      using (id = 'singleton')
      with check (id = 'singleton');
  end if;
end $$;

-- ==============================
-- 2) Audit table
-- ==============================
create table if not exists public.admin_access_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  attempted_email text,
  ip_address text,
  path text,
  reason text not null,
  user_agent text
);

create index if not exists idx_admin_access_audit_created_at
  on public.admin_access_audit (created_at desc);

alter table public.admin_access_audit enable row level security;

drop policy if exists authenticated_insert_audit on public.admin_access_audit;
drop policy if exists master_admin_read_audit on public.admin_access_audit;
drop policy if exists master_admin_delete_audit on public.admin_access_audit;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'admin_access_audit_insert'
  ) then
    create policy admin_access_audit_insert
      on public.admin_access_audit
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'admin_access_audit_read'
  ) then
    create policy admin_access_audit_read
      on public.admin_access_audit
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'admin_access_audit_delete'
  ) then
    create policy admin_access_audit_delete
      on public.admin_access_audit
      for delete
      to anon, authenticated
      using (true);
  end if;
end $$;
