-- Admin access control schema for Studio TFA
--
-- IMPORTANT:
-- 1) Replace the email placeholder below with your real master admin email.
-- 2) Run this script in Supabase SQL editor.

-- ==============================
-- 1) Settings table (singleton)
-- ==============================
create table if not exists public.admin_access_settings (
  id text primary key,
  allowed_ips text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.admin_access_settings (id, allowed_ips)
values ('singleton', '127.0.0.1')
on conflict (id) do nothing;

create or replace function public.touch_admin_access_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_admin_access_settings_updated_at on public.admin_access_settings;
create trigger trg_admin_access_settings_updated_at
before update on public.admin_access_settings
for each row
execute function public.touch_admin_access_settings_updated_at();

alter table public.admin_access_settings enable row level security;

-- Replace this email before running in production.
-- Example: 'admin@yourdomain.com'
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_settings'
      and policyname = 'master_admin_select_settings'
  ) then
    create policy master_admin_select_settings
      on public.admin_access_settings
      for select
      to authenticated
      using (lower(auth.jwt() ->> 'email') = lower('replace-with-master-admin@example.com'));
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_settings'
      and policyname = 'master_admin_upsert_settings'
  ) then
    create policy master_admin_upsert_settings
      on public.admin_access_settings
      for all
      to authenticated
      using (lower(auth.jwt() ->> 'email') = lower('replace-with-master-admin@example.com'))
      with check (lower(auth.jwt() ->> 'email') = lower('replace-with-master-admin@example.com'));
  end if;
end $$;

-- ==============================
-- 2) Audit table
-- ==============================
create table if not exists public.admin_access_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  attempted_email text,
  ip_address text,
  path text,
  reason text not null,
  user_agent text
);

create index if not exists idx_admin_access_audit_created_at
  on public.admin_access_audit (created_at desc);

alter table public.admin_access_audit enable row level security;

-- Allow any authenticated user to insert audit events.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'authenticated_insert_audit'
  ) then
    create policy authenticated_insert_audit
      on public.admin_access_audit
      for insert
      to authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'master_admin_read_audit'
  ) then
    create policy master_admin_read_audit
      on public.admin_access_audit
      for select
      to authenticated
      using (lower(auth.jwt() ->> 'email') = lower('replace-with-master-admin@example.com'));
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_access_audit'
      and policyname = 'master_admin_delete_audit'
  ) then
    create policy master_admin_delete_audit
      on public.admin_access_audit
      for delete
      to authenticated
      using (lower(auth.jwt() ->> 'email') = lower('replace-with-master-admin@example.com'));
  end if;
end $$;
