-- Studio TFA: payment callback + email confirmation upgrades

alter table public.orders
  add column if not exists razorpay_payment_id text,
  add column if not exists payment_signature text,
  add column if not exists paid_at timestamptz,
  add column if not exists confirmation_email_sent_at timestamptz;

create unique index if not exists idx_orders_payment_reference_unique
  on public.orders (payment_reference)
  where payment_reference is not null;

create index if not exists idx_orders_razorpay_payment_id
  on public.orders (razorpay_payment_id)
  where razorpay_payment_id is not null;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  event_fingerprint text not null unique,
  order_id text references public.orders(id) on delete set null,
  provider text not null default 'razorpay',
  event_type text not null,
  payment_id text,
  provider_order_id text,
  payload jsonb not null default '{}'::jsonb,
  processing_status text not null default 'processed',
  created_at timestamptz not null default now(),
  processed_at timestamptz not null default now()
);

create index if not exists idx_payment_events_order_id
  on public.payment_events(order_id);

create index if not exists idx_payment_events_event_type
  on public.payment_events(event_type);

create index if not exists idx_payment_events_provider_order_id
  on public.payment_events(provider_order_id)
  where provider_order_id is not null;

alter table public.payment_events enable row level security;

drop policy if exists payment_events_read_admin on public.payment_events;
create policy payment_events_read_admin
on public.payment_events
for select
to authenticated
using (public.has_role(array['admin', 'staff']));

drop policy if exists payment_events_write_admin on public.payment_events;
create policy payment_events_write_admin
on public.payment_events
for all
to authenticated
using (public.has_role(array['admin', 'staff']))
with check (public.has_role(array['admin', 'staff']));